#!/bin/bash

PATHS_TO_BACKUP=("$@")

# Some helpers and error handling
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
die() { rc=$1; shift; info "$*"; exit "$rc" ;}
warning_or_error() { code=$1; ret="warning"; [[ $code -gt 1 ]] && ret="error"; echo $ret; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting borg backup"

borg create                       \
     --stats                      \
     --show-version               \
     --show-rc                    \
     --filter AME                 \
     --list                       \
                                  \
     ::'{now:%Y-%m-%dT%H:%M:%S}'  \
     "${PATHS_TO_BACKUP[@]}" || die $? "borg create resulted in $(warning_or_error $?). Exiting"

info "Pruning repository"

borg prune             \
    --list             \
    --show-rc          \
    --keep-daily    14 \
    --keep-weekly   4  \
    --keep-monthly  12 \
    --keep-yearly   5   || die $? "borg prune resulted in $(warning_or_error $?). Exiting"
